#pragma once

#include <BLEUUID.h>
#include <BLEServer.h>

#define UUID_STANDARD false
#define UUID_CUSTOM true

#define BLE_NAME_MAX_LEN 31

#define BLE_STD_SERVICE_DEVICE_INFO 0x180A
#define BLE_STD_CHARACTERISTIC_MODEL_NUMBER 0x2A24
#define BLE_STD_CHARACTERISTIC_FIRMWARE_VERSION 0x2A26

#define BLE_SERVICE_OTA 0x0000
#define BLE_CHARACTERISTIC_OTA_COMMAND 0x0001
#define BLE_CHARACTERISTIC_OTA_DATA 0x0002

#define BLE_SERVICE_DEBUG 0x0100
#define BLE_CHARACTERISTIC_DEBUG_COMMAND 0x0101
#define BLE_CHARACTERISTIC_DEBUG_LOG 0x0102

#define BLE_SERVICE_CONFIG 0x0200
#define BLE_CHARACTERISTIC_CONFIG_VEHICLE_ID 0x0201
#define BLE_CHARACTERISTIC_CONFIG_BLUETOOTH_MODE 0x0202
#define BLE_CHARACTERISTIC_CONFIG_BLUETOOTH_NAME 0x0203
#define BLE_CHARACTERISTIC_CONFIG_BLUETOOTH_PIN 0x0204

#define BLE_SERVICE_VEHICLE_CATALOG 0x0300
#define BLE_CHARACTERISTIC_SUPPORTED_VEHICLE 0x0301

#define BLE_SERVICE_METRICS 0x0400
#define BLE_CHARACTERISTIC_GROUPED_METRIC_DATA 0x0401
#define BLE_DESCRIPTOR_GROUPED_METRIC_INFO 0x0402
#define BLE_CHARACTERISTIC_METRIC_MUTATOR 0x0403

#define BLE_LEN_GROUPED_METRIC_DATA 64
#define BLE_LEN_GROUPED_METRIC_INFO 96

namespace Bluetooth
{
  void begin();
  void loop();

  void setCanAdvertise(bool value);
  BLEServer *getServer();
  bool getClientConnected();
  BLEUUID uuid(bool custom, uint16_t id, uint16_t discriminator = 0x0000);
  esp_gatt_perm_t getAccessPermissions();
}