name: Build & Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      firmware_version: ${{ github.ref_name }}
    
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./dist
      
      - name: Create Release Draft
        uses: softprops/action-gh-release@v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          generate_release_notes: true
          files: |
            ./dist/*